name: Build Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Auto Fix and Build
        run: |
          # Agar files root folder mein hain toh unhe main directory mein laao ya project fix karo
          if [ -d "root" ]; then
            cp -r root/* .
          fi
          
          # Ensure essential packages are present
          flutter pub add http
          flutter pub add video_player
          flutter pub get
          
          # Build Release APK
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
